apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: 27.96.145.28:30500/default-main-test-html:dbca59f-14
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 50001
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true
        volumeMounts:
        - name: jenkins-home1
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home1
        persistentVolumeClaim:
          claimName: jenkins1-pvc
