apiVersion: v1
kind: Service
metadata:
  name: jenkins1-svc
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
    name: jenkins-web
  selector:
    app: jenkins
