apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
spec:
  selector:
    app.kubernetes.io/name: test
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
